Repository intel/media-driver, pull requests merged in 2019-07, with the labels that each got.

#642 Enable supporting p010 output on SKL
  media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
  media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
Labels: P2, VP, verifying

#656 Add VAConfigAttribMaxFrameSize query support for AVC encoding.
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#670 Set MOS GmmClientContext locally for avoiding wrong pointer.
  media_driver/linux/common/cm/cm_wrapper_os.cpp
  media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
  media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
Labels: Decode, Encode, VP, verifying

#669 [VP] Add Y800/411P support
  media_driver/agnostic/common/vp/hal/vphal_common.c
  media_driver/agnostic/common/vp/hal/vphal_common.h
  media_driver/agnostic/gen11/vp/kdll/hal_kernelrules_g11.c
  media_driver/agnostic/gen9/vp/kdll/hal_kernelrules_g9.c
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
  media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp
Labels: verifying

#665 set mpeg2 encode default fps to 30
  media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp
Labels: Encode, P2, verifying

#635 Correct error code returned from VAGetConfigAttributes
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: Decode, Encode, VP, verifying

#675 Fix the depth of RGBA image format from 24 to 32.
  media_driver/linux/gen10/ddi/media_libva_caps_g10.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
  media_driver/linux/gen8/ddi/media_libva_caps_g8.cpp
  media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp
Labels: Decode, Encode, VP, verifying

#666 Avoid invalid Max QP when AVC encoding.
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
Labels: Encode, verifying

#680 [VP] Add tile type for image creation
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#676 Update README to clarify different build mode
  README.md
  docs/media_features.md
Labels: verifying

#569 set vp8 encode max resolution to 4k
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: Encode, P2, verifying

#668 removed va enum max type VABufferTypeMax from media driver
  media_driver/linux/common/ddi/media_libva.cpp
Labels: Decode, Encode, P2, VP, verifying

#688 Fix 10bit RGB support in vaExportSurfaceHandle.
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#696 media_libva: Return P010 as a composite format
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying
