Repository intel/media-driver, pull requests merged in 2019-04, with the labels that each got.

#581 Travis: Add libva build step
  .travis.yml
Labels: verifying

#583 [Decode] Added copy range check for BDW
  media_driver/agnostic/common/codec/hal/codechal_decode_mpeg2.cpp
Labels: verifying

#391 [RFC] Add VA_RC_MB flag for VAEntrypointEncSliceLP+HEVC encoding.
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: P1, verifying

#572 Video Processing: Support XRGB in vaCreateImage.
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#355 add Y210 format vaImage
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#573 [VP]Add RGB565 support in vaCreateImage
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: P1, VP, verifying

#458 Add AYUV image format.
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#594 Adding R8G8B8 24bit packed RGB support in vaCreateImage.
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#357 add missing break in DdiMedia_CreateImage
  media_driver/linux/common/ddi/media_libva.cpp
Labels: P1, verifying

#575 Map VA_FOURCC_A2R10G10B10 to Media_Format_B10G10R10A2
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#459 add Y410 image change for CreateImage
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#518 Fix spelling of 'specify'
  media_driver/agnostic/common/os/mos_utilities.c
Labels: verifying

#584 ddi/media_libva: Distinguish VA memory type from external buffer flag
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_common.h
  media_driver/linux/common/ddi/media_libva_util.cpp
  media_driver/linux/common/vp/ddi/media_libva_vp.c
Labels: P1, verifying

#548 Add X11_FOUND flag
  media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
Labels: verifying

#474 libva_caps: remove unused VA_SURFACE_ATTRIB_MEM_TYPE_ANDROID_GRALLOC
  media_driver/linux/common/ddi/media_libva_caps.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
Labels: verifying

#490 media_ddi_encode_avc: fix the if-else logic and code style
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
Labels: verifying

#435 linux: fix build when using musl
  media_driver/linux/common/os/mos_defs_specific.h
Labels: verifying

#527 correct return value of QueryProcessingRate
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#509 [AVC Encode] add level_idc CODEC_AVC_LEVEL_1b
  media_driver/agnostic/common/codec/hal/codechal_encode_avc_base.cpp
  media_driver/agnostic/common/codec/shared/codec_def_common_avc.h
Labels: verifying

#510 remove duplicated va format to media format convertion function
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_common.h
Labels: verifying

#261 compile: fix warning, return const int is useless
  media_driver/agnostic/common/codec/hal/codechal_encode_csc_ds.cpp
  media_driver/agnostic/common/codec/hal/codechal_encode_csc_ds.h
  media_driver/agnostic/gen11/codec/hal/codechal_encode_csc_ds_g11.cpp
  media_driver/agnostic/gen11/codec/hal/codechal_encode_csc_ds_g11.h
Labels: verifying

#592 reset BRC when the target bitrate or max bitrate changed
  media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
Labels: Encode, P1, verifying

#604 ignore error status value for jpeg decode
  media_driver/agnostic/common/codec/hal/codechal_decoder.cpp
Labels: Decode, P1, verifying

#407 Fix transcoding performance issue on BDW.
  media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp
Labels: Encode, verifying

#530 [VP]Add IMC3 in DdiVp_GetColorSpaceFromMediaFormat
  media_driver/linux/common/vp/ddi/media_libva_vp.c
Labels: VP, verifying

#605 Add vp9 10bit y420 support for gen10/gen11 in sku
  media_driver/linux/gen10/ddi/media_sku_wa_g10.cpp
  media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
Labels: Decode, P2, verifying

#306 Take GetStatusReport() & GetStatusReportEntryLength() of VPP back for…
  media_driver/agnostic/common/vp/hal/vphal.cpp
Labels: VP, verifying
