Repository intel/media-driver, pull requests merged in 2019-01, with the labels that each got.

#352 [Encode] Enable max frame size for AVC encoder legacy mode
  media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp
  media_driver/agnostic/common/codec/shared/codec_def_common_encode.h
  media_driver/agnostic/common/codec/shared/codec_def_encode_avc.h
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.h
Labels: verifying

#429 [MOS] Fix incorrect Writepath parameter for user feature config file.
  media_driver/agnostic/common/os/mos_utilities.c
Labels: P2, verifying

#493 Add exec_object_async interface.
  media_driver/linux/common/os/i915/include/mos_bufmgr.h
  media_driver/linux/common/os/i915/include/mos_bufmgr_priv.h
  media_driver/linux/common/os/i915/mos_bufmgr.c
  media_driver/linux/common/os/i915/mos_bufmgr_api.c
  media_driver/linux/ult/libdrm_mock/mos_bufmgr_api_mock.c
Labels: P2, verifying

#496 Fix X11 detect support
  media_driver/linux/common/ddi/media_libva.cpp
Labels: P1, verifying

#433 [VP8] Implement frame rate in DDI according to interface
  media_driver/agnostic/common/codec/hal/codechal_debug_config_manager.cpp
  media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
Labels: P1, verifying
