Repository intel/media-driver, pull requests merged in 2019-06, with the labels that each got.

#545 8K resolution size is only for HEVC not for AVC and VP9.
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: Decode, verifying

#546 Frame split
  media_driver/agnostic/common/codec/hal/codechal_decode_scalability.cpp
  media_driver/agnostic/common/codec/hal/codechal_decode_scalability.h
  media_driver/agnostic/common/os/mos_os.h
  media_driver/agnostic/common/os/mos_utilities.c
  media_driver/agnostic/common/os/mos_utilities.h
  media_driver/agnostic/gen11/codec/hal/codechal_decode_hevc_g11.cpp
  media_driver/linux/common/os/hwinfo_linux.c
  media_driver/linux/common/os/i915/include/mos_bufmgr.h
  media_driver/linux/common/os/i915/mos_bufmgr.c
  media_driver/linux/common/os/mos_gpucontext_specific.cpp
  media_driver/linux/common/os/mos_gpucontext_specific.h
  media_driver/linux/common/os/mos_os_specific.c
  media_driver/linux/common/os/mos_os_specific.h
  media_driver/linux/gen11/ddi/media_sysinfo_g11.cpp
  media_driver/linux/ult/libdrm_mock/mos_bufmgr_mock.c
Labels: Decode, Encode, P1, verifying

#638 Fixed HEVC FEI config creation
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#649 [Encode] Enable HEVC 422 10 bit in PG mode on ICL
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.h
  media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
Labels: verifying

#648 UYVY format should use Y tiling.
  media_driver/linux/common/ddi/media_libva_util.cpp
Labels: verifying

#654 Make the width of created surface for P010, etc.
  media_driver/linux/common/ddi/media_libva_util.cpp
Labels: verifying

#615 [Encode] Add UYVY to jpeg encode convert media format to surface format.
  media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.cpp
Labels: verifying

#651 Add A2RGB10 and A2BGR10 format in vaQueryImageFormats.
  media_driver/linux/common/ddi/media_libva_caps.cpp
  media_driver/linux/gen10/ddi/media_libva_caps_g10.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
  media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp
Labels: verifying

#663 Avoid disable half of sub slices if only one sub slice.
  media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp
Labels: verifying

#660 Avoid invalid max/min qp for AVC encoding.
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
Labels: verifying

#610 vp: avoid segfault on Linux if vp failed to initialize
  media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
Labels: verifying

#658 Fix JPEG encoding based on app data or not.
  media_driver/agnostic/gen11/codec/hal/codechal_encode_jpeg_g11.cpp
Labels: verifying
