Repository intel/media-driver, pull requests merged in 2019-09, with the labels that each got.

#718 Add A2RGB10 and A2BGR10 in vaQuerySurfaceAttributes.
  media_driver/linux/common/ddi/media_libva.h
  media_driver/linux/common/ddi/media_libva_caps.cpp
  media_driver/linux/common/ddi/media_libva_caps.h
Labels: verifying

#708 check pitch from application for user ptr
  media_driver/linux/common/ddi/media_libva_util.cpp
Labels: verifying

#706 fix potential threading issue, avoid reusing existing vpp context
  media_driver/linux/common/ddi/media_libva.cpp
Labels: Decode, Encode, VP, verifying

#705 register VP8 decode reference frame
  media_driver/agnostic/common/codec/hal/codechal_decode_vp8.cpp
  media_driver/agnostic/common/codec/shared/codec_def_decode.h
  media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
  media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.h
Labels: Decode, verifying
