Repository intel/media-driver, pull requests merged in 2019-05, with the labels that each got.

#553 Added the compatible check for cumulativeQpDelta and pak pass.
  media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
Labels: Encode, verifying

#600 add Y210/AYUV/Y410 format support in vaDeriveImage.
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#241 Do not ignore -Wparentheses warning
  media_driver/agnostic/common/cm/cm_hal.cpp
  media_driver/agnostic/common/codec/hal/codechal_decoder.cpp
  media_driver/agnostic/common/codec/hal/codechal_encode_mpeg2.cpp
  media_driver/agnostic/common/codec/hal/codechal_encode_vp8.cpp
  media_driver/agnostic/common/codec/hal/codechal_vdenc_avc.cpp
  media_driver/agnostic/common/codec/hal/codechal_vdenc_hevc.cpp
  media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.cpp
  media_driver/agnostic/gen10/vp/hal/vphal_render_vebox_g10_base.cpp
  media_driver/agnostic/gen11/codec/hal/codechal_vdenc_hevc_g11.cpp
  media_driver/agnostic/gen11/vp/hal/vphal_render_vebox_g11_base.cpp
  media_driver/agnostic/gen8/codec/hal/codechal_encode_avc_g8.cpp
  media_driver/agnostic/gen8/hw/mhw_vebox_g8_X.cpp
  media_driver/agnostic/gen8/vp/hal/vphal_render_vebox_g8_base.cpp
  media_driver/agnostic/gen9/vp/hal/vphal_render_vebox_g9_base.cpp
  media_driver/agnostic/gen9_bxt/codec/hal/codechal_encode_avc_g9_bxt.cpp
  media_driver/agnostic/gen9_skl/codec/hal/codechal_encode_avc_g9_skl.cpp
  media_driver/cmake/linux/media_compile_flags_linux.cmake
  media_driver/linux/common/os/mos_os_specific.c
Labels: CM, Decode, Encode, VP, verifying

#598 Fix VC1 decoding of advanced profile.
  media_driver/agnostic/gen11/codec/hal/codechal_decode_vc1_g11.cpp
Labels: Decode, verifying

#622 Fix VP8 CQP encoding.
  media_driver/agnostic/common/codec/hal/codechal_encode_vp8.cpp
  media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
Labels: verifying

#619 Add free logic of picParams->pDeltaQp for avoiding memory leak.
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
  media_driver/linux/common/codec/ddi/media_ddi_encode_avc.h
  media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
  media_driver/linux/common/codec/ddi/media_ddi_encode_base.h
Labels: verifying

#623 Use sw swizzling on Gen11
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_util.cpp
  media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
Labels: verifying

#614 Sync i915 uAPI header to drm_next commit 7c13e5cc2391950541f41fc9ab03…
  media_driver/linux/common/os/i915/include/uapi/drm.h
  media_driver/linux/common/os/i915/include/uapi/drm_fourcc.h
  media_driver/linux/common/os/i915/include/uapi/drm_mode.h
  media_driver/linux/common/os/i915/include/uapi/i915_drm.h
  media_driver/linux/common/os/mos_os_specific.c
Labels: verifying

#633 Enable supporting p010 output on BXT
  media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
  media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
Labels: verifying

#606 Add RT formats for VP9 profile 0~3.
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: Decode, P2, verifying

#521 [Decode] Prevent mt read/write conflict
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/ddi/media_libva_util.h
Labels: Decode, verifying

#617 [Encode] Fix for race condition in AVC FEI
  media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
  media_driver/linux/common/ddi/media_libva_caps.cpp
  media_driver/linux/common/ddi/media_libva_caps.h
  media_driver/linux/common/ddi/media_libva_common.h
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.h
Labels: verifying

#607 Move the lock earlier to make surface heap status aligned when surfac…
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#631 Fix command buffer initialization for virtual engine.
  media_driver/linux/common/os/mos_gpucontext_specific.cpp
Labels: verifying
