Repository intel/media-driver, pull requests merged in 2020-06, with the labels that each got.

#889 vp: Add AYUV/Y210/Y410/P016/Y216/Y416 in DdiVp_GetColorSpaceFromMediaFormat
  media_driver/linux/common/vp/ddi/media_libva_vp.c
Labels: verifying

#954 Disable ICQ mode for HEVC VDENC.
  media_driver/linux/common/ddi/media_libva_caps.cpp
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#957 Decoder:VP9:GEN{9,10,11,12} : Fix the GPU hang due to wrong SegmentIDStreamIn & UsePrevInFindMvReferences
  media_driver/agnostic/gen10/hw/vdbox/mhw_vdbox_hcp_g10_X.cpp
  media_driver/agnostic/gen11/hw/vdbox/mhw_vdbox_hcp_g11_X.cpp
  media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_hcp_g12_X.cpp
  media_driver/agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_hcp_g9_bxt.cpp
  media_driver/agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_hcp_g9_kbl.cpp
Labels: verifying

#952 Fix renderhal and MOS-specific compile errors.
  media_driver/agnostic/gen10/renderhal/renderhal_g10.cpp
  media_driver/agnostic/gen11/renderhal/renderhal_g11.cpp
  media_driver/agnostic/gen12/renderhal/renderhal_g12.cpp
  media_driver/agnostic/gen9/renderhal/renderhal_g9.cpp
  media_driver/linux/common/os/mos_os_specific.c
Labels: verifying

#949 [VP] Correct reference number in caps
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#962 fix decode caps related issue
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#961 add HEVC VME MaxSlice caps
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#960 replace the reconstruct surface to be variant
  media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
  media_driver/linux/common/ddi/media_libva_common.cpp
  media_driver/linux/common/ddi/media_libva_common.h
Labels: Encode, verifying

#964 media_libva_caps_g12: create decoding attributes for SCC main 444 and main 10
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#966 media_libva: Fix scc-main444-10 decoding
  media_driver/linux/gen12/codec/ddi/media_ddi_decode_hevc_g12.cpp
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#968 [Decode] Fix ubuntu 16.04 build issue
  media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp
Labels: verifying

#948 [VP] Fix colorspace missing for some formats
  media_driver/linux/common/vp/ddi/media_libva_vp.c
Labels: VP, verifying
