Repository intel/media-driver, pull requests merged in 2020-04, with the labels that each got.

#884 use gmmlib caculate the NV12 surface offset
  media_driver/linux/common/ddi/media_libva.cpp
Labels: VP, verifying

#895 Revert "media_libva_caps: add VAConfigAttribEncSliceStructure caps for VAEntrypointEncSliceLP"
  media_driver/linux/common/ddi/media_libva_caps.cpp
Labels: verifying

#877 [VP] Fix memory corruption
  media_driver/agnostic/common/vp/kdll/hal_kerneldll.c
Labels: verifying

#908 media_libva_caps_g12: update VAEntrypointEncSliceLP
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#909 [Media Common]Fix performance drop issue
  media_driver/linux/common/ddi/media_libva.cpp
  media_driver/linux/common/vp/ddi/media_libva_vp.c
Labels: verifying

#904 GEN12: HEVC: Don't enable real tile if no subset parameters on Linux
  media_driver/agnostic/gen12/codec/hal/codechal_decode_hevc_g12.cpp
  media_driver/agnostic/gen12/codec/hal/codechal_decode_hevc_long_g12.cpp
  media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp
  media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.h
  media_driver/linux/common/codec/ddi/media_ddi_decode_hevc.cpp
  media_driver/linux/gen12/codec/ddi/media_ddi_decode_hevc_g12.cpp
Labels: Decode, verifying

#917 [VP] Explicitly initialize maxSrcRect of VphalRenderer
  media_driver/agnostic/common/vp/hal/vphal.cpp
  media_driver/agnostic/common/vp/hal/vphal_renderer.h
Labels: verifying

#920 [VP] Add condition to use VP in GetImage
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying
