Repository intel/media-driver, pull requests merged in 2021-08, with the labels that each got.

#1235 add project to the top-level cmake
  CMakeLists.txt
Labels: verifying

#1230 [VP] Fix 2pass CSC PROCAMP not work issue
  media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.cpp
Labels: verifying, VP

#1224 initialize the array before use it
  media_driver/agnostic/common/codec/hal/codechal_encode_sfc_base.cpp
Labels: verifying

#1221 Expose reg to disable decode scalability in release driver
  media_driver/agnostic/common/codec/hal/codechal_decode_scalability.cpp
  media_driver/agnostic/common/os/mos_os.h
  media_driver/agnostic/common/os/mos_utilities.cpp
  media_driver/agnostic/gen11/hw/vdbox/mhw_vdbox_mfx_g11_X.h
  media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp
  media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_mfx_g12_X.h
  media_driver/linux/common/os/mos_os_specific.c
Labels: verifying

#1212 [Decode][Gen12] Provide mem_types when querying surface attributes
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying

#1211 [encode]set hevc enc picture flag to be invalid for invalid reference…
  media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
Labels: verifying, Encode

#1203 cmrtlib/linux/CMakelists.txt: respect MEDIA_BUILD_FATAL_WARNINGS
  cmrtlib/linux/CMakeLists.txt
Labels: verifying

#1226 reset brc when frame rate changes for VP8e
  media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
  media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.h
Labels: verifying, Encode

#1214 [Media Common] Fix non-X11 build
  media_softlet/linux/common/ddi/media_libva_interface_next.cpp
Labels: verifying
