Repository intel/media-driver, pull requests merged in 2022-06, with the labels that each got.

#1419 [Decode] enable intensity compensation for vc1 decoding
  media_driver/linux/common/codec/ddi/media_ddi_decode_vc1.cpp
Labels: verifying

#1423 Fix driver crash with no kernel binary
  media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
Labels: verifying, VP, P2

#1420 Avoid incorrect error reporting for LDB when HierarchicalFlag > 0
  media_driver/agnostic/common/codec/hal/codechal_encode_hevc.cpp
Labels: verifying, Encode, HEVC

#1431 [Decode] Use the whole surface for processing if there is no region p…
  media_driver/linux/common/codec/ddi/media_ddi_decode_av1.cpp
  media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp
  media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp
  media_driver/linux/common/codec/ddi/media_ddi_decode_base.h
  media_driver/linux/common/codec/ddi/media_ddi_decode_hevc.cpp
  media_driver/linux/common/codec/ddi/media_ddi_decode_vp9.cpp
Labels: verifying

#1433 Modify Query VP Filters
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#1429 Optimize SCC capability report for Gen12 HEVC
  media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp
  media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Labels: verifying, Encode, HEVC

#1444 [Decode] Add more strict check for decode error
  media_driver/agnostic/common/codec/hal/codechal_decoder.cpp
Labels: verifying

#1426 [Encode] fix AV1 caps for obu size bytes support
  media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp
Labels: verifying

#1448 [Decode] Update the readme for hevc/ vp9 12bit output
  docs/media_features.md
Labels: verifying
