Repository intel/media-driver, pull requests merged in 2022-01, with the labels that each got.

#1242 Add MEDIA_BUILD_HARDENING option
  cmrtlib/linux/CMakeLists.txt
  media_driver/cmake/linux/media_compile_flags_linux.cmake
  media_driver/media_top_cmake.cmake
Labels: verifying, common

#1320 Return zero subpicture formats
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying

#1328 [VP] Enable BUILD_KERNELS on legacy platforms
  media_driver/agnostic/common/codec/kernel/merge.py
  media_driver/agnostic/gen11/codec/kernel_free/media_srcs.cmake
  media_driver/agnostic/gen11_icllp/vp/kernel_free/media_srcs.cmake
  media_driver/agnostic/gen12_tgllp/vp/kernel_free/Source/rename.py
  media_driver/agnostic/gen12_tgllp/vp/kernel_free/media_srcs.cmake
  media_driver/agnostic/media_srcs.cmake
Labels: verifying

#1321 Report HEVC features and block sizes for gen11
  media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
  media_driver/linux/gen11/ddi/media_libva_caps_g11.h
Labels: verifying, Encode, HEVC
