Repository intel/media-driver, pull requests merged in 2023-05, with the labels that each got.

#1655 Add code for old kernel compatibility
  media_softlet/linux/common/os/i915/mos_bufmgr.c
Labels: verifying

#1656 [VP9][Encode] Do not fill padding to recon surface
  media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.cpp
  media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.h
Labels: verifying, Encode

#1643 Add public build for exlude AVC/HEVC codec
  .github/workflows/ubuntu.yml
  docs/media_features.md
Labels: verifying

#1648 Fix GCC13 build errors
  media_driver/agnostic/Xe_M/Xe_XPM/hw/mhw_vebox_xe_xpm.h
  media_driver/agnostic/gen12/codec/hal/codechal_encode_csc_ds_mdf_g12.h
  media_driver/agnostic/gen12/hw/mhw_vebox_g12_X.h
  media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_generic.h
  media_driver/agnostic/gen9/codec/hal/codechal_encode_avc_g9.h
  media_driver/agnostic/gen9_skl/codec/hal/codechal_fei_hevc_g9_skl.cpp
  media_driver/media_softlet/agnostic/Xe_M/Xe_HPM/shared/mediacopy/media_copy_xe_hpm.h
  media_driver/media_softlet/agnostic/Xe_M/Xe_XPM_base/shared/mediacopy/media_copy_xe_xpm_base.h
  media_driver/media_softlet/agnostic/Xe_M/Xe_XPM_plus/shared/mediacopy/media_copy_xe_xpm_plus.h
  media_driver/media_softlet/agnostic/gen12_base/codec/hal/dec/shared/hucitf/decode_huc_packet_creator_g12.h
  media_driver/media_softlet/agnostic/m12/m12_0/shared/mediacopy/media_copy_m12_0.h
  media_softlet/agnostic/Xe_M_plus/Xe_LPM_plus_base/shared/mediacopy/media_copy_xe_lpm_plus_base.h
  media_softlet/agnostic/common/codec/hal/enc/shared/bufferMgr/encode_tracked_buffer_queue.cpp
  media_softlet/agnostic/common/codec/hal/enc/shared/bufferMgr/encode_tracked_buffer_queue.h
  media_softlet/agnostic/common/shared/media_debug_serializer.h
  media_softlet/agnostic/common/shared/scalability/media_scalability_multipipe.cpp
  media_softlet/agnostic/common/shared/scalability/media_scalability_multipipe.h
Labels: verifying, Encode, Decode
