Repository intel/media-driver, pull requests merged in 2023-03, with the labels that each got.

#1604 Disable Gen10 driver code when -DGEN10=OFF
  media_driver/agnostic/media_srcs.cmake
  media_driver/cmake/linux/media_gen_flags_linux.cmake
  media_driver/linux/media_srcs.cmake
  media_driver/media_interface/media_srcs.cmake
Labels: verifying, VP, Encode, Decode

#1622 [Decode] Close the hanle if return error to avoid file handles leak
  media_driver/linux/common/ddi/media_libva.cpp
Labels: verifying, Decode

#1607 Remove stale cmake subdirectory
  media_softlet/linux/common/media_srcs.cmake
Labels: verifying

#1613 use possible upstream definition of CCS modifier
  media_softlet/linux/Xe_M_plus/ddi/media_libva_caps_mtl_base.cpp
  media_softlet/linux/common/ddi/media_libva_util_next.cpp
Labels: verifying
