Repository intel/media-driver, pull requests merged in 2024-11, with the labels that each got.

#1866 Fixed compilation issues in Android
  cmrtlib/linux/hardware/cm_device_os.cpp
  media_driver/linux/common/ddi/media_libva.h
  media_softlet/agnostic/common/vp/hal/bufferMgr/vp_allocator.cpp
  media_softlet/agnostic/common/vp/kdll/hal_kerneldll_next.c
  media_softlet/linux/common/os/osservice/mos_utilities_specific.cpp
  media_softlet/linux/common/os/xe/mos_bufmgr_xe.c
Labels: verifying, VP

#1876 [Encode] Add Y210 caps for BMG HEVC encode
  media_softlet/linux/xe2_hpm_r0/encode/hevc/ddi/capstable_data_hevc_encode_xe2_hpm_r0_specific.h
Labels: verifying, Encode, HEVC

#1878 [Readme] Update Ubuntu link
  README.md
Labels: verifying
