Repository intel/media-driver, pull requests merged in 2025-01, with the labels that each got.

#1862 [Decode] Do not report AV1d support in free kernel build on TGLx and DG2
  media_driver/linux/Xe_M/ddi/media_sku_wa_xe.cpp
  media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
Labels: verifying, Decode, AV1

#1884 [VP] Change RGB mask and order for BMG
  media_softlet/linux/common/ddi/capstable_data_image_format_definition.h
Labels: verifying, VP

#1897 [Encode] Fix ACM multi-channel AVC encode performance degradation
  media_driver/linux/Xe_M/ddi/media_sku_wa_xe.cpp
Labels: verifying, Encode, AVC
